
resource "talos_machine_secrets" "talos" {
  talos_version = var.talos_version
}

data "talos_machine_configuration" "controller" {
  cluster_name     = "stacking"
  cluster_endpoint = "https://192.168.3.150:6443" # Management VIP shared across control planes
  machine_type     = "controlplane"
  machine_secrets  = talos_machine_secrets.talos.machine_secrets

  # Base network configuration shared by all machines
  config_patches = [
    yamlencode(local.common_machine_config),
    # Control-plane-specific configuration: VIP for high availability
    #yamlencode({
    #  machine = {
    #    network = {
    #      interfaces = [{
    #        interface = "eth0"
    #        vip = {
    #          ip = "192.168.3.150"  # Virtual IP shared across the control planes
    #        }
    #      }]
    #    }
    #  }
    #}),
    # Management VIP shared across the control planes (election via etcd).
    # NB: Layer2VIPConfig only accepts a link NAME (no deviceSelector);
    # on these virtio VMs the stable interface is "ens18".
    yamlencode({
      apiVersion = "v1alpha1"
      kind       = "Layer2VIPConfig"
      name       = "192.168.3.150"
      link       = "ens18"
    }),
    # THE BIG ONE: the inlineManifests with Cilium
    yamlencode({
      cluster = {
        network = {
          cni = {
            name = "none"
          }
        }
        proxy = {
          disabled = true
        }
      }
    }),
    # THE BIG ONE: the inlineManifests with Cilium.
    # IMPORTANT: inlineManifests are a cluster-wide config applied by the
    # control plane at bootstrap. Workers IGNORE this field, so it MUST be
    # here (controlplane) and nowhere else.
    yamlencode({
      cluster = {
        inlineManifests = [
          {
            name = "cilium"
            contents = join("---\n", [
              data.helm_template.cilium.manifest, # The YAML generated by Helm
              "# Custom load balancer configuration\n${local.cilium_external_lb_manifest}",
            ])
          }
        ]
      }
    }),
    # NB: the HostnameConfig is provided by local.common_machine_config (above).
  ]
}

data "talos_machine_configuration" "worker" {
  cluster_name     = "stacking"
  cluster_endpoint = "https://192.168.3.150:6443" # Management VIP shared across control planes
  machine_type     = "worker"
  machine_secrets  = talos_machine_secrets.talos.machine_secrets

  # Base network configuration shared by all machines
  config_patches = [
    yamlencode(local.common_machine_config),
    # NB: no inlineManifests here — it is a cluster-wide config
    # applied only by the control plane at bootstrap (see controller).
  ]
}
#
resource "talos_machine_configuration_apply" "controller" {
  for_each             = local.talos.control
  client_configuration = talos_machine_secrets.talos.client_configuration
  # Deterministic static hostname (= k8s node name) per machine.
  # By default Talos generates a `HostnameConfig: auto: stable` document that NO
  # config_patch can neutralize (strategic merge does not remove `auto`,
  # RFC6902 is not supported in multi-doc, and `auto` + `hostname` are mutually exclusive).
  # So we replace the generated document directly with a static hostname.
  machine_configuration_input = replace(
    data.talos_machine_configuration.controller.machine_configuration,
    "kind: HostnameConfig\nauto: stable",
    "kind: HostnameConfig\nhostname: talos-controlplane-${each.key}"
  )
  endpoint = each.value.address
  node     = each.value.address

  # Per-machine specific patch: static IP.
  config_patches = [
    yamlencode({
      machine = {
        network = {
          interfaces = [{
            deviceSelector = {
              driver = "virtio_net" # targets the virtio NIC, independent of the eth0/ens18 name
            }
            dhcp      = false
            addresses = ["${each.value.address}/24"]
            routes = [{
              network = "0.0.0.0/0"
              gateway = "192.168.3.1"
            }]
          }]
        }
      }
    }),
  ]
}

resource "talos_machine_configuration_apply" "worker" {
  for_each             = local.talos.worker
  client_configuration = talos_machine_secrets.talos.client_configuration
  # Deterministic static hostname (= k8s node name) per machine.
  # See the detailed explanation on the controller resource: we replace the
  # `HostnameConfig: auto: stable` document generated by Talos with a static hostname.
  machine_configuration_input = replace(
    data.talos_machine_configuration.worker.machine_configuration,
    "kind: HostnameConfig\nauto: stable",
    "kind: HostnameConfig\nhostname: talos-worker-${each.key}"
  )
  endpoint = each.value.address
  node     = each.value.address

  # Per-machine specific patch: static IP.
  config_patches = [
    yamlencode({
      machine = {
        network = {
          interfaces = [{
            deviceSelector = {
              driver = "virtio_net" # targets the virtio NIC, independent of the eth0/ens18 name
            }
            dhcp      = false
            addresses = ["${each.value.address}/24"]
            routes = [{
              network = "0.0.0.0/0"
              gateway = "192.168.3.1"
            }]
          }]
        }
      }
    }),
  ]
}
#
## Bootstrap etcd/control plane: run ONLY ONCE and on a SINGLE node.
resource "talos_machine_bootstrap" "this" {
  depends_on = [talos_machine_configuration_apply.controller["01"]]

  client_configuration = talos_machine_secrets.talos.client_configuration
  endpoint             = local.talos.control["01"].address
  node                 = local.talos.control["01"].address
}

# Admin kubeconfig retrieved from the cluster once etcd is bootstrapped.
# Consumed by the helm and kubectl providers (see provider.tf) to deploy
# in-cluster workloads (Gateway API CRDs + Traefik, see traefik.tf).
resource "talos_cluster_kubeconfig" "this" {
  depends_on = [talos_machine_bootstrap.this]

  client_configuration = talos_machine_secrets.talos.client_configuration
  endpoint             = local.talos.control["01"].address
  node                 = local.talos.control["01"].address
}
# Health gate: blocks until the control plane is actually serving before any
# in-cluster workload is applied. Without this, kubectl_manifest/helm_release
# race the API server coming up right after bootstrap (connection refused).
# skip_kubernetes_checks = true: gate on Talos/control-plane health only — the
# full k8s checks would otherwise wait on kube-proxy, which is disabled here
# (Cilium kubeProxyReplacement).
data "talos_cluster_health" "this" {
  depends_on = [
    talos_machine_configuration_apply.controller,
    talos_machine_configuration_apply.worker,
    talos_machine_bootstrap.this,
  ]

  client_configuration = talos_machine_secrets.talos.client_configuration
  control_plane_nodes  = [for n in local.talos.control : n.address]
  worker_nodes         = [for n in local.talos.worker : n.address]
  endpoints            = [for n in local.talos.control : n.address]

  skip_kubernetes_checks = true
}

data "helm_template" "cilium" {
  namespace    = "kube-system"
  name         = "cilium"
  repository   = "https://helm.cilium.io"
  chart        = "cilium"
  version      = "1.19.5"
  kube_version = "v1.36.0"
  values       = [file("${path.module}/helm/cilium-values.yaml")]
}