resource "talos_machine_secrets" "talos" {
  talos_version = var.talos_version
}

data "talos_machine_configuration" "controller" {
  cluster_name     = var.cluster_name
  cluster_endpoint = "https://${var.vip}:6443" # Management VIP shared across control planes
  machine_type     = "controlplane"
  machine_secrets  = talos_machine_secrets.talos.machine_secrets

  # Base network configuration shared by all machines
  config_patches = [
    yamlencode(local.common_machine_config),
    # Management VIP shared across the control planes (election via etcd).
    # NB: Layer2VIPConfig only accepts a link NAME (no deviceSelector);
    # on these virtio VMs the stable interface is "ens18".
    yamlencode({
      apiVersion = "v1alpha1"
      kind       = "Layer2VIPConfig"
      name       = var.vip
      link       = var.vip_link
    }),
    # Disable Talos' built-in CNI and kube-proxy: Cilium owns both
    # (kubeProxyReplacement). Cilium itself is NOT injected here as an
    # inlineManifest anymore — it is a real helm_release (see the cilium module)
    # so that `terraform apply` reconciles upgrades/value changes (inlineManifests
    # only apply once at bootstrap and never reconcile).
    yamlencode({
      cluster = {
        network = {
          cni = {
            name = "none"
          }
        }
        proxy = {
          disabled = true
        }
      }
    }),
    # NB: the HostnameConfig is provided by local.common_machine_config (above).
  ]
}

data "talos_machine_configuration" "worker" {
  cluster_name     = var.cluster_name
  cluster_endpoint = "https://${var.vip}:6443" # Management VIP shared across control planes
  machine_type     = "worker"
  machine_secrets  = talos_machine_secrets.talos.machine_secrets

  # Base network configuration shared by all machines
  config_patches = [
    yamlencode(local.common_machine_config),
    # NB: no inlineManifests here — it is a cluster-wide config
    # applied only by the control plane at bootstrap (see controller).
  ]
}

resource "talos_machine_configuration_apply" "controller" {
  for_each             = local.control
  client_configuration = talos_machine_secrets.talos.client_configuration
  # The VM must exist (and be booted into maintenance mode) before we can apply
  # config to it. Making this explicit also fixes DESTROY ordering: without it,
  # the proxmox VMs had NO dependency edge to the Talos/helm chain, so Terraform
  # tore the VMs down in parallel with helm_release/kubectl_manifest — the API
  # then vanished mid-destroy and those resources hung on "connection refused".
  # With this edge the VMs are destroyed LAST (after helm uninstall completes).
  depends_on = [proxmox_virtual_environment_vm.talos_nodes]
  # Deterministic static hostname (= k8s node name) per machine.
  # By default Talos generates a `HostnameConfig: auto: stable` document that NO
  # config_patch can neutralize (strategic merge does not remove `auto`,
  # RFC6902 is not supported in multi-doc, and `auto` + `hostname` are mutually exclusive).
  # So we replace the generated document directly with a static hostname.
  machine_configuration_input = replace(
    data.talos_machine_configuration.controller.machine_configuration,
    "kind: HostnameConfig\nauto: stable",
    "kind: HostnameConfig\nhostname: talos-controlplane-${each.key}"
  )
  endpoint = each.value.address
  node     = each.value.address

  # Per-machine specific patch: static IP.
  config_patches = [
    yamlencode({
      machine = {
        network = {
          interfaces = [{
            deviceSelector = {
              driver = "virtio_net" # targets the virtio NIC, independent of the eth0/ens18 name
            }
            dhcp      = false
            addresses = ["${each.value.address}/24"]
            routes = [{
              network = "0.0.0.0/0"
              gateway = var.gateway
            }]
          }]
        }
      }
    }),
  ]
}

resource "talos_machine_configuration_apply" "worker" {
  for_each             = local.worker
  client_configuration = talos_machine_secrets.talos.client_configuration
  # See controller resource: required for apply ordering AND for clean destroy
  # ordering (VMs torn down last, after helm/kubectl).
  depends_on = [proxmox_virtual_environment_vm.talos_nodes]
  # Deterministic static hostname (= k8s node name) per machine.
  # See the detailed explanation on the controller resource: we replace the
  # `HostnameConfig: auto: stable` document generated by Talos with a static hostname.
  machine_configuration_input = replace(
    data.talos_machine_configuration.worker.machine_configuration,
    "kind: HostnameConfig\nauto: stable",
    "kind: HostnameConfig\nhostname: talos-worker-${each.key}"
  )
  endpoint = each.value.address
  node     = each.value.address

  # Per-machine specific patch: static IP.
  config_patches = [
    yamlencode({
      machine = {
        network = {
          interfaces = [{
            deviceSelector = {
              driver = "virtio_net" # targets the virtio NIC, independent of the eth0/ens18 name
            }
            dhcp      = false
            addresses = ["${each.value.address}/24"]
            routes = [{
              network = "0.0.0.0/0"
              gateway = var.gateway
            }]
          }]
        }
      }
    }),
    # Workers are the Longhorn storage nodes: partition+format the dedicated
    # second disk (scsi1 → /dev/sdb) and mount it at /var/lib/longhorn (which the
    # kubelet extraMount in common_machine_config then exposes to Longhorn).
    yamlencode({
      machine = {
        disks = [{
          device = "/dev/sdb"
          partitions = [{
            mountpoint = "/var/lib/longhorn"
          }]
        }]
      }
    }),
  ]
}

## Bootstrap etcd/control plane: run ONLY ONCE and on a SINGLE node.
resource "talos_machine_bootstrap" "this" {
  depends_on = [talos_machine_configuration_apply.controller["01"]]

  client_configuration = talos_machine_secrets.talos.client_configuration
  endpoint             = local.control["01"].address
  node                 = local.control["01"].address
}

# Admin kubeconfig retrieved from the cluster once etcd is bootstrapped.
# Consumed by the helm and kubectl providers (configured at the root) to deploy
# in-cluster workloads (Cilium, Gateway API CRDs + Traefik).
resource "talos_cluster_kubeconfig" "this" {
  depends_on = [talos_machine_bootstrap.this]

  client_configuration = talos_machine_secrets.talos.client_configuration
  endpoint             = local.control["01"].address
  node                 = local.control["01"].address
}

# NB: there is intentionally NO `data.talos_cluster_health` gate here.
# We hit a hard deadlock with it: as of Talos v1.13.x a node's MachineStatus
# stays in `booting` (unmetConditions: nodeReady) until the node is Ready, and
# `data.talos_cluster_health` waits for "all nodes to finish boot sequence" — a
# check that `skip_kubernetes_checks` does NOT skip. But a node only becomes Ready
# once the CNI is in, and Cilium is installed AFTER this gate → the health check
# never releases → apply fails with "cluster health check failed", Cilium never
# installs, nodes stay NotReady. (Older Talos released the check before Ready,
# which is why this used to work.)
#
# The apiserver poll below is the real gate and is sufficient: it proves the API
# is serving (all in-cluster resources need that) WITHOUT requiring node Ready.
# The kube-apiserver static pod runs hostNetwork, so it answers on the VIP before
# any CNI exists. Every in-cluster resource depends on this via the module output.
resource "terraform_data" "wait_for_apiserver" {
  depends_on = [
    talos_machine_configuration_apply.controller,
    talos_machine_configuration_apply.worker,
    talos_machine_bootstrap.this,
  ]

  # Re-run the wait whenever the cluster (and thus its endpoint/CA) is recreated.
  triggers_replace = [talos_cluster_kubeconfig.this.id]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    environment = {
      ENDPOINT = talos_cluster_kubeconfig.this.kubernetes_client_configuration.host
    }
    command = <<-EOT
      for i in $(seq 1 60); do
        code=$(curl -sk -o /dev/null -w '%%{http_code}' --max-time 5 "$ENDPOINT/version" || true)
        if [ -n "$code" ] && [ "$code" != "000" ]; then
          echo "kube-apiserver serving at $ENDPOINT (HTTP $code)"; exit 0
        fi
        echo "waiting for kube-apiserver at $ENDPOINT... ($i/60)"; sleep 5
      done
      echo "kube-apiserver never became reachable at $ENDPOINT" >&2; exit 1
    EOT
  }
}
